# -*- coding: utf-8 -*-
"""digit_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AG7MUgC-Awb3czzDMC-bbQqDoWfTBkoh
"""

from google.colab import files
uploaded = files.upload()

import numpy as np

import csv

import pandas as pd
df=pd.read_csv('mnist_train.csv')

df2=pd.read_csv('mnist_test.csv')

I_L=np.ones((784,1))
      W_1 = np.random.randn(128,784) * np.sqrt(2/784)
      W_2 = np.random.randn(64,128) * np.sqrt(2/128)
      W_3 = np.random.randn(10,64) * np.sqrt(2/64)


      B_1=np.zeros((128,1))

      B_2=np.zeros((64,1))

      B_3=np.zeros((10,1))
      Y=np.ones((10,1))

class nn:
  def __init__(self,w_1,w_2,w_3,b_1,b_2,b_3):

     self.w_1=w_1
     self.w_2=w_2
     self.w_3=w_3
     self.b_1=b_1
     self.b_2=b_2
     self.b_3=b_3

  def forward(self,i_l):
    self.i_l=i_l
    self.Z_1=(np.matmul(self.w_1,self.i_l)+self.b_1)
    self.A_1=np.maximum(0, self.Z_1)

    self.Z_2=(np.matmul(self.w_2,self.A_1)+self.b_2)
    self.A_2=(np.maximum(0,self.Z_2))
    self.Z_3=(np.matmul(self.w_3,self.A_2)+self.b_3)
    self.A_3=( np.exp(self.Z_3) / np.sum(np.exp(self.Z_3)))
    return(self.A_3.argmax(axis=0))


  def backward(self,y):
    self.y=y


    self.M=(self.Z_2>0).astype(int)
    self.N=(self.Z_1>0).astype(int)
    V3=(self.A_3-self.y)
    V2=(np.transpose(self.w_3)@V3)*self.M
    V1=(np.transpose(self.w_2)@V2)*self.N
    dJ_W3=V3@np.transpose(self.A_2)
    dJ_W2=V2@np.transpose(self.A_1)
    dJ_W1=V1@np.transpose(self.i_l)
    dJ_B3=V3
    dJ_B2=V2
    dJ_B1=V1


    self.w_3=self.w_3-(0.005*dJ_W3)
    self.b_3=self.b_3-(0.005*dJ_B3)
    self.w_2=self.w_2-(0.005*dJ_W2)
    self.b_2=self.b_2-(0.005*dJ_B2)
    self.w_1=self.w_1-(0.005*dJ_W1)
    self.b_1=self.b_1-(0.005*dJ_B1)

for i in range(0,60000):
  NN=nn(W_1,W_2,W_3,B_1,B_2,B_3)
  for j in range(1,785):
    I_L[j-1,0]=(df.iloc[i,j]/255)
  for l in range(0,10):
    if df.iloc[i,0]==l :
      Y[l,0]=1
    else:
      Y[l,0]=0
  NN.forward(I_L)
  NN.backward(Y)
  W_1=NN.w_1
  W_2=NN.w_2
  W_3=NN.w_3
  B_1=NN.b_1
  B_2=NN.b_2
  B_3=NN.b_3

np.save("W_1.npy",W_1)
np.save("W_2.npy",W_2)
np.save("W_3.npy",W_3)
np.save("B_1.npy",B_1)
np.save("B_2.npy",B_2)
np.save("B_3.npy",B_3)

NN=nn(W_1,W_2,W_3,B_1,B_2,B_3)
for j in range(1,785):
 I_L[j-1,0]=(df2.iloc[4,j]/255)
NN.forward(I_L)

